language: node_js

node_js:
  - "8"
  - "10"
  - "12"

notifications:
  email:
    recipients:
      - martin@pipedrive.com
      - kristo.kaiv@pipedrive.com
    on_success: change
    on_failure: change

sudo: false
